- _name_: mamba
  causal: true
  dropout: null
  bias: True
  add_bias_kv: False
  add_zero_attn: False
  kdim: null
  vdim: null
  rotary: false
- _name_: ff
  expand: 4
  activation: gelu
  dropout: ${...dropout} # Same as null
